### ISSUE TITLE
Getting some errors

### ISSUE THREAD

**Issue by smolinari** [orientechnologies/orientdb-docker#10]
Hi,

When I run the ODB docker container (latest) in a docker-compose.yml file with `docker-compose up`, I get these messages returned.
```
orientdb    | 2016-05-17 06:35:18:660 WARNI Not enough physical memory available for DISKCACHE: 2,002MB (heap=494MB). Set lower Maximum Heap (-Xmx setting on JVM) and restart OrientDB. Now running with DISKCACHE=256MB [orientechnologies]
orientdb    | 2016-05-17 06:35:18:668 INFO  OrientDB config DISKCACHE=-541MB (heap=494MB os=2,002MB disk=17,247MB) [orientechnologies]
orientdb    | 2016-05-17 06:35:18:785 INFO  Loading configuration from: /orientdb/config/orientdb-server-config.xml... [OServerConfigurationLoaderXml]
orientdb    | 2016-05-17 06:35:19:070 INFO  OrientDB Server v2.1.16 (build 2.1.x@r13efec7610a3eceb539db5ebfb31dea2534aa819; 2016-04-19 10:56:07+0000) is starting up... [OServer]
orientdb    | 2016-05-17 06:35:19:074 INFO  Databases directory: /orientdb/databases [OServer]
orientdb    | 2016-05-17 06:35:19:106 INFO  Listening binary connections on 0.0.0.0:2424 (protocol v.32, socket=default) [OServerNetworkListener]
orientdb    | 2016-05-17 06:35:19:110 INFO  Listening http connections on 0.0.0.0:2480 (protocol v.10, socket=default) [OServerNetworkListener]
orientdb    | 2016-05-17 06:35:19:132 INFO  Installing dynamic plugin 'studio-2.1.zip'... [OServerPluginManager]
orientdb    | 2016-05-17 06:35:19:239 INFO  Installing GREMLIN language v.2.6.0 - graph.pool.max=50 [OGraphServerHandler]
orientdb    | 2016-05-17 06:35:19:240 INFO  [OVariableParser.resolveVariables] Error on resolving property: distributed [orientechnologies]
orientdb    | 2016-05-17 06:35:19:242 INFO  Installing Script interpreter. WARN: authenticated clients can execute any kind of code into the server by using the following allowed languages: [sql] [OServerSideScriptInterpreter]
```

And then docker-composer times out with:

```
ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).
```

If I set `COMPOSE_HTTP_TIMEOUT to a higher value it just sits with the messages given above, then times out later. 

Is this normal procedure?

Scott

**Comment by robfrank** [comment]
This error seems more related to compose  and docker than to OrientDB. I don't think that compose interact directly with ODB, at least it talks with docker (daemon).  
Can you attach your compose  to the issue?

**Comment by smolinari** [comment]
Do you mean the `docker-compose.yml file`?

This is it.

```
version: '2'

services:
  spider:
    build: .
    container_name: spider
    ports:
      - "9000:9000"
    links:
      - orientdb
    volumes:
      - /src:/spider/src
      - /tests:/spider/test

  orientdb:
    image: orientdb:latest
    container_name: orientdb
    environment:
      ORIENTDB_ROOT_PASSWORD: rootpwd
    ports:
       - "2424:2424"
       - "2480:2480"
```
