### ISSUE TITLE
Latest docker image has basic auth restricting from doing anything from the studio

### ISSUE THREAD

**Issue by decebal** [orientechnologies/orientdb-docker#26]
I am setting up the docker image using the environment variables, but when the basic auth comes up I don't have any other credentials that I can setup

**Comment by robfrank** [comment]
I don't understand very well the issue. BTW, I try to give a solution. 
AFIU you run the container providing  password for the root user.
On the landing page, with these credentials, you can create a new database, and then login with admin/admin credential on the just created database. Studio documentation:
http://orientdb.com/docs/last/Studio-Home-page.html

**Comment by decebal** [comment]
Thanks for the answer Rob, but it's really frustrating for me at this point as I am new to this and I can't find a image that just works.

Steps to reproduce the issue I'm having:

1. use `orientdb:latest` with docker-compose, open the studio interface
2. try to create a new database from the studio interface, introduce database name, username and password
3. basic auth pops up .. tried admin:admin , root:root, root:{ORIENTDB_ROOT_PASSWORD}

**Comment by robfrank** [comment]
Please, provide the docker compose configuration. I guess you're not setting the root password.

**Comment by decebal** [comment]
Thanks for drilling down on this Rob, you're right, there were issues raised about the root password not being set, I have set the password, to check it I also got a `sh` prompt inside the container and my environment has it set.

This is my yaml file, in case you find it useful:
```
    dev-orientdb:
        image: orientdb:latest
        environment:
            - ORIENTDB_ROOT_PASSWORD=root
            - ORIENTDB_NODE_NAME=my_shiny_database
        volumes:
            - '../../containers/db/orientdb:/orientdb/databases'
            - '../../containers/orientdb/backup:/orientdb/backup'
        ports:
          - "2424:2424"
          - "2480:2480"
        expose:
          - "2424"
          - "2480"
        entrypoint:
          - "server.sh"
```

From my understanding after going through some configuration files, it has nothing to do with that password, but I don't know where the basic auth comes from.. maybe it's from the studio install (the zip file).
