### ISSUE TITLE
Unable to restore backups from console inside container

### ISSUE THREAD

**Issue by stubbegianni** [orientechnologies/orientdb-docker#33]
Hello, 

I'm running orient inside a docker container. I enabled automatic backups and I want to try and restore a backup. 

The problem is when I'm trying to restore the backup the file is not found: `./bin/backup/20171109084000.zip (No such file or directory)` 

When I connect to the console and I enter `pwd` I get `/orientdb`. So when I connect to the docker container through a shell (`sudo docker exec -i -t <container id> /bin/sh`) and I navigate to the /orientdb/bin/backup folder, the file is there. I tried many other file locations but none seems to work. 

Is this an issue with orient in docker or orient itself?

**Comment by stubbegianni** [comment]
Can it be confirmed this is a bug? I don't want to put Orient to production without being sure I can restore a backup.

**Comment by robfrank** [comment]
are you providing a volume to the container where to persist backups?

**Comment by stubbegianni** [comment]
Yes I am, I'm starting my docker container with ansible, my config is the following: 

```
- name: setup orient docker container
  docker_container:
    name: orientdb
    image: orientdb:latest
    command: "/orientdb/bin/server.sh -Ddistributed=false"
    published_ports:
      - 2424:2424
      - 2480:2480
    network_mode: host
    volumes:
      - "/orientdb/config:/orientdb/config"
      - "/orientdb/databases:/orientdb/databases"
      - "/orientdb/backup:/orientdb/bin/backup"
    env:
      ORIENTDB_ROOT_PASSWORD: "<password here>"
      ORIENTDB_NODE_NAME: "{{ ansible_hostname }}"
      ORIENTDB_OPTS_MEMORY: "-Xms20G -Xmx20G"
    recreate: yes
    state: started
```
