### ISSUE TITLE
overriding configuration params in docker-compose.yml

### ISSUE THREAD

**Issue by sbcd90** [orientechnologies/orientdb-docker#37]
Hello,
I see from the documentation that I can override configuration params upon startup using -D as shown below.

```
docker run -d --name orientdb -p 2424:2424 -p 2480:2480 \
    -v <config_path>:/orientdb/config \
    -v <databases_path>:/orientdb/databases \
    -v <backup_path>:/orientdb/backup \
    -e ORIENTDB_ROOT_PASSWORD=rootpwd \
    -e ORIENTDB_NODE_NAME=odb1 \
    orientdb /orientdb/bin/server.sh  -Ddistributed=true
```

Is it also possible to override configuration params like this in docker-compose.yml?
Can someone please help?

**Comment by robfrank** [comment]
In a compose file:
```
version: '2'
services:
    orientdb:
        image: orientdb:latest
        volumes:
            - ~/volumes/orientdb/databases:/orientdb/databases
        environment:
            ORIENTDB_ROOT_PASSWORD: rootpwd
        ports:
            - 2480:2480
            - 2424:2424
```
