### ISSUE TITLE
docker-compose orientdb3.0.5

### ISSUE THREAD

**Issue by cuvelierm** [orientechnologies/orientdb-docker#50]
I am currently trying to setup OrientDB 3.0.5 in a distributed mode using docker-compose.

After adding my first server(which starts up perfectly all right).
I am not able to use the configured `ORIENTDB_ROOT_PASSWORD`.

My current docker-compose.yml

```
version: '3'
services:
  orientdb3:
    image: orientdb:3.0.5
    networks:
    - default
    environment:
      ORIENTDB_ROOT_PASSWORD: "randomrootpassword123"
      ORIENTDB_NODE_NAME: "odb1"
      ORIENTDB_OPTS_MEMORY: "-Xms4G -Xmx4G"
    ports:
      - 2480:2480
      - 2424:2424
    logging:
      driver: json-file
      options:``
        max-size: "200k"
        max-file: "10"
    restart: on-failure
```
Starting and connecting will work fine, but the `randomrootpassword123` I entered is not able to be used.

Any help would be appreciated and if more info is needed feel free to ask.
